//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_Garage
    {
        public int ParkingMemberID { get; set; }
        public int GarageID { get; set; }
        public int ReservedParkingSpace { get; set; }
        public int ID { get; set; }
    
        public virtual Garage Garage { get; set; }
        public virtual ParkingMember ParkingMember { get; set; }
    }
}
