//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParkingMember()
        {
            this.Member_Garage = new HashSet<Member_Garage>();
        }
    
        public int ParkingMemberID { get; set; }
        public string ParkingMemberName { get; set; }
        public string ParkingMemberCarMake { get; set; }
        public string ParkingMemberCarModel { get; set; }
        public int ParkingMemberCarYear { get; set; }
        public string ParkingMemberPlate { get; set; }
        public Nullable<bool> ParkingMemberElite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member_Garage> Member_Garage { get; set; }
    }
}
