//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPark.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartParkEntities : DbContext
    {
        public SmartParkEntities()
            : base("name=SmartParkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Garage> Garages { get; set; }
        public virtual DbSet<Member_Garage> Member_Garage { get; set; }
        public virtual DbSet<ParkingMember> ParkingMembers { get; set; }
    }
}
